name: ItemCommands
main: com.Cutch.bukkit.ICmds.ItemCommands
version: 1.12
author: Cutch
commands:
  icmd:
    description: Add Hotkey like functionality
    usage: /icmd [add|change|remove|swap|list|reload]